version: '3.9'

services:
  drupal:
    image: drupal
    ports:
      - 80:80
    volumes:
      - type: volume
        source: nfs
        target: /var/www/html
        volume:
          nocopy: true
    restart: always
    privileged: true

volumes:
  nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},nfsvers=4,rw,nolock,soft
      device: :/var/nfs