version: "3.9"
services:
  drupal:
    image: drupal
    ports:
      - 80:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
      - ./conf/my.cnf:/etc/my.cnf
volumes:
  drupal: