version: '3.9'
services:
  apache:
    build: 
      context: .
      dockerfile: Dockerfile
    image: httpd:2.4
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    - ./ssl/server.crt:/usr/local/apache2/ssl/server.crt
    - ./ssl/server.key:/usr/local/apache2/ssl/server.key